- name: Install Docker
  hosts: control-center
  become: true

  vars:
    docker_edition: "ce"
    docker_package_state: present

    docker_service_manage: true
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted

    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present

  roles:
    - geerlingguy.docker
