version: "3.8"

services:
  docker-registry:
    image: registry:2
    container_name: docker_registry
    restart: always
    ports:
      - "9445:5000"
    volumes:
      - /opt/docker-registry/data:/var/lib/registry
      - /opt/docker-registry/registry-config.yml:/etc/docker/registry/config.yml
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  docker-registry-ui:
    image: joxit/docker-registry-ui:2.5.7
    container_name: docker_registry_ui
    restart: always
    ports:
      - "9444:80"
    environment:
      - REGISTRY_TITLE=Mistiop Image Registry
      - REGISTRY_URL=http://docker-registry:5000
      - DELETE_IMAGES=true
    depends_on:
      - docker-registry
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
